### ISSUE TITLE
PF2E spell attack and damage fail when rolled using the module

### ISSUE THREAD

**Issue by shemetz** [shemetz/roll-from-compendium#23]
These have been failing recently (as of v5.9.0), due to some problem with `damage.kinds`:

> foundry.js:753 TypeError: Failed data preparation for Actor.tcUAvJHcKGi8TBBl.Item.G13AidYNtUCIz8lc. object is not iterable (cannot read property Symbol(Symbol.iterator))
    at new Set (<anonymous>)
    at _SpellPF2e2.prepareBaseData (pf2e.mjs:306:94283)
    at _SpellPF2e2.prepareData (foundry.js:14209:12)

> TypeError: d.kinds.has is not a function
    at pf2e.mjs:306:96139
    at Array.some (<anonymous>)
    at _SpellPF2e2.getRollOptions (pf2e.mjs:306:96123)
    at _CharacterPF2e.getRollContext (pf2e.mjs:306:156212)

I tried to debug and fix it but I got stuck.  The code changes that led to it seem very recent (3 days ago).  Here's hoping this gets fixed without my needing to do anything :(

**Comment by shemetz** [comment]
Fixed in v1.7.3
