### ISSUE TITLE
AGE system compatibility bug:  Can't share any item

### ISSUE THREAD

**Issue by kamil-merdanov** [shemetz/roll-from-compendium#26]
Hello there and thank you for your module!

For some reason I can't share any item (from the directory/compendium).

```
Quick Send To Chat | Sending item to chat: Assault Rifles
quick-send-to-chat.js:121 Quick Send To Chat | temporarily binding item to actor: Assault Rifles + -> (Quick Send To Chat)
quick-send-to-chat.js:164 Quick Send To Chat | undoing temporary binding of item to actor: Assault Rifles - -> (Quick Send To Chat)
dice.js:72 Uncaught (in promise) TypeError: undefined. Cannot read properties of null (reading 'ctrlKey')
[Detected 2 packages: system:age-system, roll-from-compendium]
    at Module.ageRollCheck (dice.js:72:16)
    at ageSystemItem.roll (ageSystemItem.js:739:14)
    at rollDependingOnSystem (quick-send-to-chat.js:226:17)
    at rollItem (quick-send-to-chat.js:203:10)
    at quickSendToChat (quick-send-to-chat.js:17:36)
    at Object.onclick (menu-buttons.js:25:14)
    at HTMLAnchorElement.<anonymous> (foundry.js:5941:16)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
```

Any chance you can fix this? 

I'm using fvtt ver. 11.315 and [AGE-System Unofficial](https://foundryvtt.com/packages/age-system).

**Comment by shemetz** [comment]
Added in v1.7.6 :)
