### ISSUE TITLE
Add button to journal image pages

### ISSUE THREAD

**Issue by shemetz** [shemetz/roll-from-compendium#29]
suggested in:  https://discord.com/channels/880968862240239708/880969174661353484/1255401014643654777

**Comment by shemetz** [comment]
done in v1.8.0

**Comment by Yosoy-Ed** [comment]
Hello, this is not working in Foundry v14 365, Pf2e 8.4.0 (Havent tried other system,but seems general foundry).

The page title is sent to chat, but no image is shown, instead it says "undefined"

<img width="373" height="384" alt="Image" src="https://github.com/user-attachments/assets/286e00ff-5ec0-4104-960b-626ede7bb692" />

console log error:

```foundry.mjs:1560 Error: The renderChatMessage hook is deprecated. Please use renderChatMessageHTML instead, which now passes an HTMLElement argument instead of jQuery.
Deprecated since Version 13
Backwards-compatible support will be removed in Version 15
    at Object.logCompatibilityWarning (foundry.mjs:1548:17)
    at ChatMessagePF2e.renderHTML (foundry.mjs:48984:21)
    at async ChatMessagePF2e.xt (message.ts:69:28)
    at async ChatMessagePF2e.<anonymous> (_shared.ts:65:18)
    at async ChatMessagePF2e.renderHTML (pf2e.mjs:28718:11)
    at async #postNotification (foundry.mjs:130653:19)
logCompatibilityWarning @ foundry.mjs:1560
renderHTML @ foundry.mjs:48984
await in renderHTML
call_wrapped @ libWrapper-wrapper.js:511
xt @ message.ts:69
call_wrapper @ libWrapper-wrapper.js:639
(anonymous) @ libwrapper.js:35
(anonymous) @ _shared.ts:65
wrapper @ libwrapper.js:35
call_wrapper @ libWrapper-wrapper.js:639
(anonymous) @ libWrapper-wrapper.js:193
renderHTML @ pf2e.mjs:28718
await in renderHTML
renderMessage @ foundry.mjs:130801
#postNotification @ foundry.mjs:130653
notify @ foundry.mjs:130438
#postOne @ foundry.mjs:130731
await in #postOne
#try @ foundry.mjs:7641
(anonymous) @ foundry.mjs:7614
add @ foundry.mjs:7612
postOne @ foundry.mjs:130465
_onCreate @ foundry.mjs:49095
_onCreate @ pf2e.mjs:28794
(anonymous) @ foundry.mjs:80866
(anonymous) @ foundry.mjs:80872
#handleCreateDocuments @ foundry.mjs:80872
await in #handleCreateDocuments
#handleResponse @ foundry.mjs:81319
_createDocuments @ foundry.mjs:80764
await in _createDocuments
create @ foundry.mjs:80379
await in create
createDocuments @ foundry.mjs:14987
create @ foundry.mjs:15111
onClick @ menu-buttons.js:118
#onClickItem @ foundry.mjs:29569
(anonymous) @ foundry.mjs:29524
